# Generated by Django 4.1.5 on 2023-01-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=50)),
                ('first_tweet_timestamp', models.DateTimeField()),
                ('last_tweet_timestamp', models.DateTimeField()),
                ('word_cloud', models.TextField()),
            ],
        ),
    ]
